// This file is "iap_data.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `iap_data.dart` with the code generated by Freezed
part 'iap_data.freezed.dart';
// optional: Since our IAPData class is serializable, we must add this line.
// But if IAPData was not serializable, we could skip it.
part 'iap_data.g.dart';

@freezed
class IAPData with _$IAPData {
  @JsonSerializable(includeIfNull: false)
  const factory IAPData({
    required bool? isRemovedAd,
    }) = _IAPData;

  factory IAPData.fromJson(Map<String, dynamic> json) =>
      _$IAPDataFromJson(json);
}