// This file is "score_data.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `score_data.dart` with the code generated by Freezed
part 'score_data.freezed.dart';
// optional: Since our ScoreData class is serializable, we must add this line.
// But if ScoreData was not serializable, we could skip it.
part 'score_data.g.dart';

@freezed
abstract class ScoreData with _$ScoreData {
  @JsonSerializable(includeIfNull: false)
  const factory ScoreData({
    required List<int> bestScore,
    required int maxStreak,
  }) = _ScoreData;

  factory ScoreData.fromJson(Map<String, Object?> json)
      => _$ScoreDataFromJson(json);
}
