// This file is "setting.dart"
import 'package:bit_math/screens/playing_page/stages/actor/bitman.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `setting.dart` with the code generated by Freezed
part 'setting.freezed.dart';
// optional: Since our Setting class is serializable, we must add this line.
// But if Setting was not serializable, we could skip it.
part 'setting.g.dart';

@freezed
class Setting with _$Setting {
  const factory Setting({
    // environment,ui setting
    required bool isSound,
    required bool isBGM,
    required bool isHapticFeedback,
    required bool isFixedJoystick,
    required bool isLeftJoystick,
    // bitman setting
    required BitmanWeapon selectedWeapon,
    required BitmanHelmet selectedHelmet,
    required BitmanColor color,
    required String bitmanName,
  }) = _Setting;

  factory Setting.fromJson(Map<String, Object?> json)
      => _$SettingFromJson(json);
}