// This file is "user_data.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `user_data.dart` with the code generated by Freezed
part 'user_data.freezed.dart';
// optional: Since our UserData class is serializable, we must add this line.
// But if ScoreData was not serializable, we could skip it.
part 'user_data.g.dart';

/*
  UserDataにnullableなプロパティはfirestoreがサポートしている型であれば、
  いつでも追加できる。理由は
  1. firestoreで書き込む際にはfirestoreは新しいフィールドを柔軟に作るから
  2. firestoreで読み込む際には、新しいプロパティを追加する前のデータも@JsonSerializable(includeIfNull: false)
    によって、フィールドがなくても、nullとして読み込まれるから
*/
@freezed
class UserData with _$UserData {
  @JsonSerializable(includeIfNull: false)
  const factory UserData({
    required String? deviceId,
    required String name,
    required int bestScore,
  }) = _UserData;

  factory UserData.fromJson(Map<String, Object?> json)
      => _$UserDataFromJson(json);
}


// class UserData {
//   final String? deviceId;
//   final String name;
//   final int bestScore;

//   UserData({
//     required this.deviceId,
//     required this.name,
//     required this.bestScore,
//   });

//   UserData copyWith({
//     String? deviceId,
//     String? name,
//     int? bestScore,
//   }){
//     return UserData(
//       deviceId: deviceId ?? this.deviceId, 
//       name: name ?? this.name, 
//       bestScore: bestScore ?? this.bestScore);
//   }

//   factory UserData.fromFirestore(DocumentSnapshot<Map<String, dynamic>> snapshot) {
//     final data = snapshot.data();
//     return UserData(
//       deviceId: data?['deviceId'],
//       name: data?['name'] ?? '',
//       bestScore: data?['bestScore'] ?? 0,
//     );
//   }

//   factory UserData.fromMap(Map<String, dynamic> data) {
//     return UserData(
//       deviceId: data['deviceId'],
//       name: data['name'] ?? '',
//       bestScore: data['bestScore'] ?? 0,
//     );
//   }

//   Map<String, dynamic> toFirestore() {
//     return {
//       'deviceId': deviceId,
//       'name': name,
//       'bestScore': bestScore,
//     };
//   }
// }

