// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAVHXhS-6XtiWL4pUEwypCOVd0cJQLjoA',
    appId: '1:900557872438:web:3674563fc049a4f1442797',
    messagingSenderId: '900557872438',
    projectId: 'bit-math-dbfb2',
    authDomain: 'bit-math-dbfb2.firebaseapp.com',
    storageBucket: 'bit-math-dbfb2.appspot.com',
    measurementId: 'G-NZ7CYMZEL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-P5lUj9OviSqK9XESXpGkOZdv8oDzoi4',
    appId: '1:900557872438:android:f26366f378261873442797',
    messagingSenderId: '900557872438',
    projectId: 'bit-math-dbfb2',
    storageBucket: 'bit-math-dbfb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoCx3iX5rCCpQ3NyTXRaW9nnPsXsPzlUI',
    appId: '1:900557872438:ios:cdd9d559fcdfef8b442797',
    messagingSenderId: '900557872438',
    projectId: 'bit-math-dbfb2',
    storageBucket: 'bit-math-dbfb2.appspot.com',
    iosBundleId: 'com.daikikaneda.bitMath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoCx3iX5rCCpQ3NyTXRaW9nnPsXsPzlUI',
    appId: '1:900557872438:ios:6baaf0882a6744af442797',
    messagingSenderId: '900557872438',
    projectId: 'bit-math-dbfb2',
    storageBucket: 'bit-math-dbfb2.appspot.com',
    iosBundleId: 'com.daikikaneda.bitMath.RunnerTests',
  );
}
